name: publish
on:
  push:
    branch:
      - "release"

jobs:
  publish:
    - name: build
      run: |
        npm ci
        tsc
    - name: version
      run: cat package.json | jq -r '.version'
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: build artifacts
      run: npm run pack
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mm-linux
        asset_name: Merrymake CLI for Linux
        asset_content_type: application/octet-stream
    - name: upload macos artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mm-macos
        asset_name: Merrymake CLI for MacOS
        asset_content_type: application/octet-stream
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mm-win.exe
        asset_name: Merrymake CLI for Windows
        asset_content_type: application/octet-stream
